### ISSUE TITLE
Remove unicode char in keyword arguments (or offer an alternative) ?

### ISSUE THREAD

**Issue by franckgaga** [JuliaControl/ModelPredictiveControl.jl#61]
@baggepinnen 
There is a palpable hate against unicode characters, especially in keyword arguments of public functions. Some keyword arguments of this package use them e.g.: `σP_0`, `σQ`, `σR` and `x̂_0`. I personally like them for the conciseness. It is also well known that σ is a standard deviation, and `^`, a modifier for an estimated value. Should we offer an [alternative](https://discourse.julialang.org/t/unicode-a-bad-idea-in-general/99897/36?u=franckgaga), something like:
```julia
function SteadyKalmanFilter(
    model::Linmodel;
    i_ym = 1:model.ny,
    σQ = fill(1/model.nx, model.nx),
    σR = fill(1, length(i_ym)),
    nint_u = 0,
    σQint_u = fill(1, max(sum(nint_u), 0)),
    nint_ym = default_nint(model, i_ym, nint_u),
    σQint_ym = fill(1, max(sum(nint_ym), 0))
    sigmaR = σR,                  # new kwarg 
    sigmaQ = σQ,                  # new kwarg
    sigmaQint_u = σQint_u,        # new kwarg
    sigmaQint_ym = σQint_ym       # new kwarg
)    
    # estimated covariances matrices (variance = σ²) :
    Q̂  = Hermitian(diagm(NT[sigmaQ;  sigmaQint_u;  sigmaQint_ym ].^2), :L)
    R̂  = Hermitian(diagm(NT[sigmaR;].^2), :L)
    return SteadyKalmanFilter{NT, SM}(model, i_ym, nint_u, nint_ym, Q̂ , R̂)
end
```
and something similar with `x̂_0` and `xhat_0` ?

**Comment by baggepinnen** [comment]
I guess it's good practice to have non-unicode API in general. I also like Unicode, but there are certainly cases where it's awkward or hard to type. Most editors _can_ be configured to make it easy, but one might not always be using a computer on which everything has been customized to ones liking. 

I was in a previously in a position where I transitioned between multiple different computers in a lab, all running Julia (on different operating systems) to control robots and perform sys.id., and in this context it would have been a hassle to configure everything to work as well as on my main development machine.
