### ISSUE TITLE
MPC getinfo results

### ISSUE THREAD

**Issue by caxelrud** [JuliaControl/ModelPredictiveControl.jl#76]
Hi, I am getting the following results when using getinfo().
N is 200.
it looks like, for multivariable inputs and outputs, the results are flattened but clamped to the size N.
```
info=getinfo(mpc)
info[:Rhaty ]
julia>
200-element Vector{Float64}:
 50.0
 30.0
  ⋮
 50.0
 30.0
```

**Comment by franckgaga** [comment]
I'm not able to reproduce, are you using the last version v.0.21.3 ? Did you did you solve the mpc problem at least one time with `moveinput!` ?

Here's the result on my side:

```julia
using ModelPredictiveControl, ControlSystemsBase
mpc = LinMPC(LinModel(append(tf(2,[10,1]), tf(3,[5, 1])), 1.0), Hp=200);
u = moveinput!([2,10]);
info = getinfo!(mpc);
info[:Rhaty]
```
results in:
```
400-element Vector{Float64}:
  2.0
 10.0
  2.0
 10.0
  2.0
  ⋮
  2.0
 10.0
  2.0
 10.0
```

**Comment by caxelrud** [comment]
I found a bug in my testing code.
All looks good now so, please, disregard my issue.

**Comment by franckgaga** [comment]
Alright, let me know if there is another issue !
